def import_pods
  pod 'TRVSKit', :path => '../'
end

target :ios do
  platform :ios, '7.0'
  link_with 'iOS Tests'
  import_pods
end

target :osx do
  platform :osx, '10.9'
  link_with 'OSX Tests'
  import_pods
end
